app:
  domain: "https://api.kiwoom.com"
  mock_domain: "https://mockapi.kiwoom.com"
  token_expiry: 3600

# db:
#   host: "localhost"
#   port: 5432
#   database: "kiwoom_db"
#   user: "postgres"
#   password: "postgres_password"

database:
  engine: sqlite
  name: trading_bot.db
  user: null
  password: null
  host: null
  port: null

log:
  level: "INFO"
  file: "kiwoom_auto_trader.log"
